# Generated by Django 3.1.7 on 2021-03-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('passport', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринговый балл')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_begin_rotation', models.DateField(blank=True, verbose_name='дата начала ротации')),
                ('date_end_rotation', models.DateField(blank=True, verbose_name='Дата окончания ротации')),
                ('title', models.CharField(max_length=150, verbose_name='Название предложения')),
                ('type', models.IntegerField(choices=[(1, 'Потребительский'), (2, 'Ипотечный'), (3, 'Автокредит')], default=1, verbose_name='Тип предложения')),
                ('min_scoring', models.IntegerField(default=0, verbose_name='Минимальный скоринговый балл')),
                ('max_scoring', models.IntegerField(default=0, verbose_name='Максимальный скоринговый балл')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbrf_id', models.IntegerField(default=0, verbose_name='ID CBRF')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('reg_num', models.IntegerField(default=0, verbose_name='Регистрационный номер')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sended', models.DateTimeField(verbose_name='Дата отправки')),
                ('status', models.IntegerField(choices=[(1, 'Новая'), (2, 'Отправлена'), (3, 'Получена'), (4, 'Одобрено'), (5, 'Отказано'), (6, 'Выдано')], default=1, verbose_name='Статус')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.checklist', verbose_name='Анкета')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.partner', verbose_name='Партнёр'),
        ),
    ]
